<?xml version="1.0" encoding="utf-8"?><Database Name="balabar1_Tubeless" Class="DataClassesAutenticatorDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=balabarkaran.com;Initial Catalog=balabar1_Tubeless;Persist Security Info=True;User ID=balabar1_Tubeless_Develop" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="balabar1_TubelessConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="balabar1_Tubeless_Develop.Tbl_ApplicationStore" Member="Tbl_ApplicationStores">
    <Type Name="Tbl_ApplicationStore">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IDApplication" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StoreName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="isFree" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="URL" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Tbl_ApplicationStore_Tbl_DeviceApp" Member="Tbl_DeviceApps" ThisKey="ID" OtherKey="IDApplicationStore" Type="Tbl_DeviceApp" />
      <Association Name="Tbl_ApplicationStore_Tbl_ApplicationStorePermission" Member="Tbl_ApplicationStorePermissions" ThisKey="ID" OtherKey="ApplicationStoreId" Type="Tbl_ApplicationStorePermission" />
      <Association Name="Tbl_Application_Tbl_ApplicationStore" Member="Tbl_Application" ThisKey="IDApplication" OtherKey="ID" Type="Tbl_Application" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_WalletTransaction" Member="Tbl_WalletTransactions">
    <Type Name="Tbl_WalletTransaction">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IDUser" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDUserCreator" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IDApplication" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="Zarib" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TransactionTypeCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RefrenceNo" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MetaData" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IP" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="isWalletTransaction" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Tbl_Application_Tbl_WalletTransaction" Member="Tbl_Application" ThisKey="IDApplication" OtherKey="ID" Type="Tbl_Application" IsForeignKey="true" />
      <Association Name="Tbl_DetailsLookup_Tbl_WalletTransaction" Member="Tbl_DetailsLookup" ThisKey="TransactionTypeCode" OtherKey="Id" Type="Tbl_DetailsLookup" IsForeignKey="true" />
      <Association Name="Tbl_User_Tbl_WalletTransaction" Member="Tbl_User" ThisKey="IDUser" OtherKey="Id" Type="Tbl_User" IsForeignKey="true" />
      <Association Name="Tbl_User_Tbl_WalletTransaction1" Member="Tbl_User1" ThisKey="IDUserCreator" OtherKey="Id" Type="Tbl_User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="balabar1_Tubeless_Develop.Tbl_DeviceApp" Member="Tbl_DeviceApps">
    <Type Name="Tbl_DeviceApp">
      <Column Name="IDDevice" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDApplication" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CreateOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastRunApplicationOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IDApplicationStore" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Token" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Tbl_ApplicationStore_Tbl_DeviceApp" Member="Tbl_ApplicationStore" ThisKey="IDApplicationStore" OtherKey="ID" Type="Tbl_ApplicationStore" IsForeignKey="true" />
      <Association Name="Tbl_Application_Tbl_DeviceApp" Member="Tbl_Application" ThisKey="IDApplication" OtherKey="ID" Type="Tbl_Application" IsForeignKey="true" />
      <Association Name="Tbl_Application_Tbl_DeviceApp1" Member="Tbl_Application1" ThisKey="IDApplication" OtherKey="ID" Type="Tbl_Application" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="balabar1_Tubeless_Develop.Tbl_ElectedUsers" Member="Tbl_ElectedUsers">
    <Type Name="Tbl_ElectedUser">
      <Column Name="F_UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="F_ApplicationId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="F_StateId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsElected" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ElectedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Comment" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Location" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Tel" Type="System.String" DbType="NChar(12)" CanBeNull="true" />
      <Column Name="Star" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsDelete" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Tbl_Application_Tbl_ElectedUser" Member="Tbl_Application" ThisKey="F_ApplicationId" OtherKey="ID" Type="Tbl_Application" IsForeignKey="true" />
      <Association Name="Tbl_DetailsLookup_Tbl_ElectedUser" Member="Tbl_DetailsLookup" ThisKey="F_StateId" OtherKey="Id" Type="Tbl_DetailsLookup" IsForeignKey="true" />
      <Association Name="Tbl_User_Tbl_ElectedUser" Member="Tbl_User" ThisKey="F_UserId" OtherKey="Id" Type="Tbl_User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="balabar1_Tubeless_Develop.Tbl_Faved_Posts" Member="Tbl_Faved_Posts">
    <Type Name="Tbl_Faved_Post">
      <Column Name="IDUser" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDPost" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Tbl_Post_Tbl_Faved_Post" Member="Tbl_Post" ThisKey="IDPost" OtherKey="Id" Type="Tbl_Post" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Tbl_User_Tbl_Faved_Post" Member="Tbl_User" ThisKey="IDUser" OtherKey="Id" Type="Tbl_User" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="balabar1_Tubeless_Develop.Tbl_Loginto_DeviceSettings" Member="Tbl_Loginto_DeviceSettings">
    <Type Name="Tbl_Loginto_DeviceSetting">
      <Column Name="DeviceID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AutoAdd" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ReciveNotifs" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Tbl_Device_Tbl_Loginto_DeviceSetting" Member="Tbl_Device" ThisKey="DeviceID" OtherKey="Id" Type="Tbl_Device" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="balabar1_Tubeless_Develop.Tbl_Loginto_DeviceSites" Member="Tbl_Loginto_DeviceSites">
    <Type Name="Tbl_Loginto_DeviceSite">
      <Column Name="DeviceID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SiteID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LastLoginDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LoginCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AddedAuto" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Tbl_Device_Tbl_Loginto_DeviceSite" Member="Tbl_Device" ThisKey="DeviceID" OtherKey="Id" Type="Tbl_Device" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="balabar1_Tubeless_Develop.Tbl_Loginto_Site" Member="Tbl_Loginto_Sites">
    <Type Name="Tbl_Loginto_Site">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="JoinDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AdminName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="AdminMobile" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CategoryID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Tbl_DetailsLookup_Tbl_Loginto_Site" Member="Tbl_DetailsLookup" ThisKey="CategoryID" OtherKey="Id" Type="Tbl_DetailsLookup" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="balabar1_Tubeless_Develop.Tbl_Post_Image" Member="Tbl_Post_Images">
    <Type Name="Tbl_Post_Image">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PostId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Picture" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="isDeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="isDisabled" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Tbl_Post_Tbl_Post_Image" Member="Tbl_Post" ThisKey="PostId" OtherKey="Id" Type="Tbl_Post" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="balabar1_Tubeless_Develop.tbl_UsersDevices" Member="tbl_UsersDevices">
    <Type Name="tbl_UsersDevice">
      <Column Name="IDDevice" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDUser" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Tbl_Device_tbl_UsersDevice" Member="Tbl_Device" ThisKey="IDDevice" OtherKey="Id" Type="Tbl_Device" IsForeignKey="true" />
      <Association Name="Tbl_User_tbl_UsersDevice" Member="Tbl_User" ThisKey="IDUser" OtherKey="Id" Type="Tbl_User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="balabar1_Tubeless_Develop.Tbl_Visited_Posts" Member="Tbl_Visited_Posts">
    <Type Name="Tbl_Visited_Post">
      <Column Name="IDUser" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDPost" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Tbl_Post_Tbl_Visited_Post" Member="Tbl_Post" ThisKey="IDPost" OtherKey="Id" Type="Tbl_Post" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Tbl_User_Tbl_Visited_Post" Member="Tbl_User" ThisKey="IDUser" OtherKey="Id" Type="Tbl_User" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_Applications" Member="Tbl_Applications">
    <Type Name="Tbl_Application">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NameFa" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="StatementFa" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TextFa" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NameEn" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="StatementEn" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TextEn" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NameTu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="StatementTu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TextTu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="url" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LogoPicture" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="AppTypeCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Priority" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Tbl_Application_Tbl_ApplicationStore" Member="Tbl_ApplicationStores" ThisKey="ID" OtherKey="IDApplication" Type="Tbl_ApplicationStore" />
      <Association Name="Tbl_Application_Tbl_WalletTransaction" Member="Tbl_WalletTransactions" ThisKey="ID" OtherKey="IDApplication" Type="Tbl_WalletTransaction" />
      <Association Name="Tbl_Application_Tbl_DeviceApp" Member="Tbl_DeviceApps" ThisKey="ID" OtherKey="IDApplication" Type="Tbl_DeviceApp" />
      <Association Name="Tbl_Application_Tbl_DeviceApp1" Member="Tbl_DeviceApps1" ThisKey="ID" OtherKey="IDApplication" Type="Tbl_DeviceApp" />
      <Association Name="Tbl_Application_Tbl_ElectedUser" Member="Tbl_ElectedUsers" ThisKey="ID" OtherKey="F_ApplicationId" Type="Tbl_ElectedUser" />
      <Association Name="Tbl_Application_Tbl_ApplicationVersion" Member="Tbl_ApplicationVersions" ThisKey="ID" OtherKey="ApplicationID" Type="Tbl_ApplicationVersion" />
      <Association Name="Tbl_Application_Tbl_Message" Member="Tbl_Messages" ThisKey="ID" OtherKey="ApplicationID" Type="Tbl_Message" />
      <Association Name="Tbl_Application_Tbl_Post" Member="Tbl_Posts" ThisKey="ID" OtherKey="IDApplication" Type="Tbl_Post" />
      <Association Name="Tbl_DetailsLookup_Tbl_Application" Member="Tbl_DetailsLookup" ThisKey="AppTypeCode" OtherKey="Id" Type="Tbl_DetailsLookup" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_ApplicationVersion" Member="Tbl_ApplicationVersions">
    <Type Name="Tbl_ApplicationVersion">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ApplicationID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="VersionCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="VersionName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="VersionConfig" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Price" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="StatementFa" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="StatementEn" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="StatementTu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DownloadUrl" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DownloadCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Views" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Tbl_ApplicationVersion_Tbl_UserApp" Member="Tbl_UserApps" ThisKey="Id" OtherKey="IDApplicationVersion" Type="Tbl_UserApp" />
      <Association Name="Tbl_Application_Tbl_ApplicationVersion" Member="Tbl_Application" ThisKey="ApplicationID" OtherKey="ID" Type="Tbl_Application" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_CategoriesLookUp" Member="Tbl_CategoriesLookUps">
    <Type Name="Tbl_CategoriesLookUp">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Tbl_CategoriesLookUp_Tbl_DetailsLookup" Member="Tbl_DetailsLookups" ThisKey="Id" OtherKey="IDCategoryLookUp" Type="Tbl_DetailsLookup" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_DetailsLookup" Member="Tbl_DetailsLookups">
    <Type Name="Tbl_DetailsLookup">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IDParent" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IDCategoryLookUp" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ImageUrl" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="icon" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Selectable" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Tbl_DetailsLookup_Tbl_WalletTransaction" Member="Tbl_WalletTransactions" ThisKey="Id" OtherKey="TransactionTypeCode" Type="Tbl_WalletTransaction" />
      <Association Name="Tbl_DetailsLookup_Tbl_ElectedUser" Member="Tbl_ElectedUsers" ThisKey="Id" OtherKey="F_StateId" Type="Tbl_ElectedUser" />
      <Association Name="Tbl_DetailsLookup_Tbl_Loginto_Site" Member="Tbl_Loginto_Sites" ThisKey="Id" OtherKey="CategoryID" Type="Tbl_Loginto_Site" />
      <Association Name="Tbl_DetailsLookup_Tbl_Application" Member="Tbl_Applications" ThisKey="Id" OtherKey="AppTypeCode" Type="Tbl_Application" />
      <Association Name="Tbl_DetailsLookup_Tbl_Message" Member="Tbl_Messages" ThisKey="Id" OtherKey="Type" Type="Tbl_Message" />
      <Association Name="Tbl_DetailsLookup_Tbl_User" Member="Tbl_Users" ThisKey="Id" OtherKey="UserTypeCode" Type="Tbl_User" />
      <Association Name="Tbl_DetailsLookup_Tbl_ApplicationStorePermission" Member="Tbl_ApplicationStorePermissions" ThisKey="Id" OtherKey="UserTypeCode" Type="Tbl_ApplicationStorePermission" />
      <Association Name="Tbl_CategoriesLookUp_Tbl_DetailsLookup" Member="Tbl_CategoriesLookUp" ThisKey="IDCategoryLookUp" OtherKey="Id" Type="Tbl_CategoriesLookUp" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_Devices" Member="Tbl_Devices">
    <Type Name="Tbl_Device">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DeviceID" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Serial" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Model" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="BuildId" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="AndroidVersion" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="AndroidAPI" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Manufacturer" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Brand" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Board" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Display" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IP" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="IDUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PushNotificaionToken" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Tbl_Device_Tbl_Loginto_DeviceSetting" Member="Tbl_Loginto_DeviceSetting" ThisKey="Id" OtherKey="DeviceID" Type="Tbl_Loginto_DeviceSetting" Cardinality="One" />
      <Association Name="Tbl_Device_Tbl_Loginto_DeviceSite" Member="Tbl_Loginto_DeviceSites" ThisKey="Id" OtherKey="DeviceID" Type="Tbl_Loginto_DeviceSite" />
      <Association Name="Tbl_Device_tbl_UsersDevice" Member="tbl_UsersDevices" ThisKey="Id" OtherKey="IDDevice" Type="tbl_UsersDevice" />
      <Association Name="Tbl_User_Tbl_Device" Member="Tbl_User" ThisKey="IDUser" OtherKey="Id" Type="Tbl_User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_Message" Member="Tbl_Messages">
    <Type Name="Tbl_Message">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ApplicationID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SenderUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ReciverUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Type" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Text" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MetaData" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ShowForSender" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ShowForReciver" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Readed" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Tbl_Application_Tbl_Message" Member="Tbl_Application" ThisKey="ApplicationID" OtherKey="ID" Type="Tbl_Application" IsForeignKey="true" />
      <Association Name="Tbl_DetailsLookup_Tbl_Message" Member="Tbl_DetailsLookup" ThisKey="Type" OtherKey="Id" Type="Tbl_DetailsLookup" IsForeignKey="true" />
      <Association Name="Tbl_User_Tbl_Message" Member="Tbl_User" ThisKey="ReciverUserID" OtherKey="Id" Type="Tbl_User" IsForeignKey="true" />
      <Association Name="Tbl_User_Tbl_Message1" Member="Tbl_User1" ThisKey="SenderUserID" OtherKey="Id" Type="Tbl_User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_Post_Amounts" Member="Tbl_Post_Amounts">
    <Type Name="Tbl_Post_Amount">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdPost" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Text" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Tbl_Post_Tbl_Post_Amount" Member="Tbl_Post" ThisKey="IdPost" OtherKey="Id" Type="Tbl_Post" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_Posts" Member="Tbl_Posts">
    <Type Name="Tbl_Post">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IDUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IDUserModifiedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IDApplication" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="TitlePicture" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Text" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="TextPicture" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TypeCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StateCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CityCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PriceForVsit" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ReciveMessage" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PublishDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ExpireDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IDUserAcceptor" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AcceptDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="VisitCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IP" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="Tbl_Post_Tbl_Faved_Post" Member="Tbl_Faved_Posts" ThisKey="Id" OtherKey="IDPost" Type="Tbl_Faved_Post" />
      <Association Name="Tbl_Post_Tbl_Post_Image" Member="Tbl_Post_Images" ThisKey="Id" OtherKey="PostId" Type="Tbl_Post_Image" />
      <Association Name="Tbl_Post_Tbl_Visited_Post" Member="Tbl_Visited_Posts" ThisKey="Id" OtherKey="IDPost" Type="Tbl_Visited_Post" />
      <Association Name="Tbl_Post_Tbl_Post_Amount" Member="Tbl_Post_Amounts" ThisKey="Id" OtherKey="IdPost" Type="Tbl_Post_Amount" />
      <Association Name="Tbl_Application_Tbl_Post" Member="Tbl_Application" ThisKey="IDApplication" OtherKey="ID" Type="Tbl_Application" IsForeignKey="true" />
      <Association Name="Tbl_User_Tbl_Post" Member="Tbl_User" ThisKey="IDUser" OtherKey="Id" Type="Tbl_User" IsForeignKey="true" />
      <Association Name="Tbl_User_Tbl_Post1" Member="Tbl_User1" ThisKey="IDUserModifiedBy" OtherKey="Id" Type="Tbl_User" IsForeignKey="true" />
      <Association Name="Tbl_User_Tbl_Post2" Member="Tbl_User2" ThisKey="IDUserAcceptor" OtherKey="Id" Type="Tbl_User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_UserApps" Member="Tbl_UserApps">
    <Type Name="Tbl_UserApp">
      <Column Name="IDUser" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDApplicationVersion" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LastLoginOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IDUserMoaref" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Tbl_ApplicationVersion_Tbl_UserApp" Member="Tbl_ApplicationVersion" ThisKey="IDApplicationVersion" OtherKey="Id" Type="Tbl_ApplicationVersion" IsForeignKey="true" />
      <Association Name="Tbl_User_Tbl_UserApp" Member="Tbl_User" ThisKey="IDUser" OtherKey="Id" Type="Tbl_User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_Users" Member="Tbl_Users">
    <Type Name="Tbl_User">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserCode" Type="System.Int32" DbType="Int" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="CodeMelli" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PhoneNumberConfirmed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SimCardId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(550)" CanBeNull="true" />
      <Column Name="Family" Type="System.String" DbType="NVarChar(550)" CanBeNull="true" />
      <Column Name="Avatar" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ProfileImage" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="UserTypeCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Tbl_User_Tbl_WalletTransaction" Member="Tbl_WalletTransactions" ThisKey="Id" OtherKey="IDUser" Type="Tbl_WalletTransaction" />
      <Association Name="Tbl_User_Tbl_WalletTransaction1" Member="Tbl_WalletTransactions1" ThisKey="Id" OtherKey="IDUserCreator" Type="Tbl_WalletTransaction" />
      <Association Name="Tbl_User_Tbl_ElectedUser" Member="Tbl_ElectedUsers" ThisKey="Id" OtherKey="F_UserId" Type="Tbl_ElectedUser" />
      <Association Name="Tbl_User_Tbl_Faved_Post" Member="Tbl_Faved_Posts" ThisKey="Id" OtherKey="IDUser" Type="Tbl_Faved_Post" />
      <Association Name="Tbl_User_tbl_UsersDevice" Member="tbl_UsersDevices" ThisKey="Id" OtherKey="IDUser" Type="tbl_UsersDevice" />
      <Association Name="Tbl_User_Tbl_Visited_Post" Member="Tbl_Visited_Posts" ThisKey="Id" OtherKey="IDUser" Type="Tbl_Visited_Post" />
      <Association Name="Tbl_User_Tbl_Device" Member="Tbl_Devices" ThisKey="Id" OtherKey="IDUser" Type="Tbl_Device" />
      <Association Name="Tbl_User_Tbl_Message" Member="Tbl_Messages" ThisKey="Id" OtherKey="ReciverUserID" Type="Tbl_Message" />
      <Association Name="Tbl_User_Tbl_Message1" Member="Tbl_Messages1" ThisKey="Id" OtherKey="SenderUserID" Type="Tbl_Message" />
      <Association Name="Tbl_User_Tbl_Post" Member="Tbl_Posts" ThisKey="Id" OtherKey="IDUser" Type="Tbl_Post" />
      <Association Name="Tbl_User_Tbl_Post1" Member="Tbl_Posts1" ThisKey="Id" OtherKey="IDUserModifiedBy" Type="Tbl_Post" />
      <Association Name="Tbl_User_Tbl_Post2" Member="Tbl_Posts2" ThisKey="Id" OtherKey="IDUserAcceptor" Type="Tbl_Post" />
      <Association Name="Tbl_User_Tbl_UserApp" Member="Tbl_UserApps" ThisKey="Id" OtherKey="IDUser" Type="Tbl_UserApp" />
      <Association Name="Tbl_User_Tbl_Wallet" Member="Tbl_Wallets" ThisKey="Id" OtherKey="IDUser" Type="Tbl_Wallet" />
      <Association Name="Tbl_DetailsLookup_Tbl_User" Member="Tbl_DetailsLookup" ThisKey="UserTypeCode" OtherKey="Id" Type="Tbl_DetailsLookup" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_Wallet" Member="Tbl_Wallets">
    <Type Name="Tbl_Wallet">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IDUser" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(18,0)" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ModifiedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="IP" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Association Name="Tbl_User_Tbl_Wallet" Member="Tbl_User" ThisKey="IDUser" OtherKey="Id" Type="Tbl_User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="balabar1_Tubeless_Develop.report_ContactUsMessages" Member="report_ContactUsMessages">
    <Type Name="report_ContactUsMessage">
      <Column Name="UserCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(550)" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Text" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MetaData" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="balabar1_Tubeless_Develop.Viw_WalletTransaction2" Member="Viw_WalletTransaction2s">
    <Type Name="Viw_WalletTransaction2">
      <Column Name="TransactionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDUser" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDApplication" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TransactionCreatorName" Type="System.String" DbType="NVarChar(550)" CanBeNull="true" />
      <Column Name="TransactionCreatorFamily" Type="System.String" DbType="NVarChar(550)" CanBeNull="true" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="TransactionTypeCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TransactionTypeName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ImageUrl" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="icon" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="RefrenceNo" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MetaData" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IDPost" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PostTitle" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="balabar1_Tubeless_Develop.report_transactions" Member="report_transactions">
    <Type Name="report_transaction">
      <Column Name="IDUser" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDUserCreator" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NameFa" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="Zarib" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TransactionTypeCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="RefrenceNo" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MetaData" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="balabar1_Tubeless_Develop.report_Users" Member="report_Users">
    <Type Name="report_User">
      <Column Name="UserCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="NameFa" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Model" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="AndroidVersion" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="AndroidAPI" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Manufacturer" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Brand" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="StoreName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="balabar1_Tubeless_Develop.View_loginto_users_site_lists" Member="View_loginto_users_site_lists">
    <Type Name="View_loginto_users_site_list">
      <Column Name="AndroidID" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SiteCode" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DeviceID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="LastLoginDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LoginCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AddedAuto" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="balabar1_Tubeless_Develop.Viw_AppStore" Member="Viw_AppStores">
    <Type Name="Viw_AppStore">
      <Column Name="typeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="type" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="companyID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="company" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ApplicationID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NameFa" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="VersionName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NameEn" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ImageUrl" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="icon" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DownloadCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Views" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DownloadUrl" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="balabar1_Tubeless_Develop.Viw_ElectedUserList" Member="Viw_ElectedUserLists">
    <Type Name="Viw_ElectedUserList">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CountPosts" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IDApplication" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserCreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="F_UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="F_ApplicationId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="F_StateId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsElected" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ElectedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Comment" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Star" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="ElectedUsersIsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ElectedUsersIsDelete" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="StateName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(550)" CanBeNull="true" />
      <Column Name="Family" Type="System.String" DbType="NVarChar(550)" CanBeNull="true" />
      <Column Name="Avatar" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ProfileImage" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="PhoneNumberConfirmed" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UserCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CodeMelli" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="SimCardId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UserTypeCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UsersIsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UsersIsDelete" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Location" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Tel" Type="System.String" DbType="NChar(12)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="balabar1_Tubeless_Develop.Viw_PostDetails" Member="Viw_PostDetails">
    <Type Name="Viw_PostDetail">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IDApplication" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="TypeCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TypeName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ImageUrl" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="icon" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="StateCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StateName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CityCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CityName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PriceForVsit" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ReciveMessage" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PublishDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ExpireDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="AcceptDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="VisitCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TitlePicture" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TextPicture" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="balabar1_Tubeless_Develop.Viw_postList" Member="Viw_postLists">
    <Type Name="Viw_postList">
      <Column Name="IDPost" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatorIDUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatorUserCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatorName" Type="System.String" DbType="NVarChar(550)" CanBeNull="true" />
      <Column Name="CreatorFamily" Type="System.String" DbType="NVarChar(550)" CanBeNull="true" />
      <Column Name="CreatorAvatar" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="IDApplication" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="PostTypeCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PostTypeName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="StateCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StateName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CityCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CityName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PriceForVsit" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ReciveMessage" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PublishDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ExpireDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VisitCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="TitlePicture" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="balabar1_Tubeless_Develop.Viw_Site_AppList" Member="Viw_Site_AppLists">
    <Type Name="Viw_Site_AppList">
      <Column Name="ApplicationID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NameFa" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="StatementFa" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TextFa" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LogoPicture" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NameEn" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="StatementEn" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="VersionCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="VersionName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Price" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DownloadCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Views" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StoreName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="isFree" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="URL" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="AppTypeCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CompanyCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Company" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CompanyUrl" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CompanyIcon" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Priority" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ApplicationVersionStatement" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DownloadUrl" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MainUrl" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ImageUrl" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="icon" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="balabar1_Tubeless_Develop.Viw_Site_Cat_level_1" Member="Viw_Site_Cat_level_1s">
    <Type Name="Viw_Site_Cat_level_1">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ImageUrl" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="icon" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="balabar1_Tubeless_Develop.Viw_Site_Cat_level_2" Member="Viw_Site_Cat_level_2s">
    <Type Name="Viw_Site_Cat_level_2">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IDParent" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ImageUrl" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="icon" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="balabar1_Tubeless_Develop.Viw_Site_MainPostList" Member="Viw_Site_MainPostLists">
    <Type Name="Viw_Site_MainPostList">
      <Column Name="IDApplication" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ApplicationName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PostId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="TitlePicture" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Text" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="TextPicture" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CatName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CatIcon" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SecoundCatName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SecoundCatIconName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ReciveMessage" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PublishDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ExpireDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="AcceptDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="VisitCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="HeaderName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="balabar1_Tubeless_Develop.Viw_userDevices" Member="Viw_userDevices">
    <Type Name="Viw_userDevice">
      <Column Name="IDUser" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="CodeMelli" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(550)" CanBeNull="true" />
      <Column Name="Family" Type="System.String" DbType="NVarChar(550)" CanBeNull="true" />
      <Column Name="IDDevice" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DeviceID" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Serial" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Model" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="BuildId" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="AndroidVersion" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="AndroidAPI" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Manufacturer" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Brand" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Board" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Display" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IP" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="PhoneNumberConfirmed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="balabar1_Tubeless_Develop.Viw_WalletTransaction" Member="Viw_WalletTransactions">
    <Type Name="Viw_WalletTransaction">
      <Column Name="TransactionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDUser" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDApplication" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TransactionCreatorName" Type="System.String" DbType="NVarChar(550)" CanBeNull="true" />
      <Column Name="TransactionCreatorFamily" Type="System.String" DbType="NVarChar(550)" CanBeNull="true" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="TransactionTypeCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TransactionTypeName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ImageUrl" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="icon" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="RefrenceNo" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MetaData" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="balabar1_Tubeless_Develop.Tbl_ApplicationStorePermissions" Member="Tbl_ApplicationStorePermissions">
    <Type Name="Tbl_ApplicationStorePermission">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ApplicationStoreId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsPostFree" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SendImageInPost" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsViewFree" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UserTypeCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Tbl_ApplicationStore_Tbl_ApplicationStorePermission" Member="Tbl_ApplicationStore" ThisKey="ApplicationStoreId" OtherKey="ID" Type="Tbl_ApplicationStore" IsForeignKey="true" />
      <Association Name="Tbl_DetailsLookup_Tbl_ApplicationStorePermission" Member="Tbl_DetailsLookup" ThisKey="UserTypeCode" OtherKey="Id" Type="Tbl_DetailsLookup" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="balabar1_Tubeless_Develop.Sp_MyPostList" Method="Sp_MyPostList">
    <Parameter Name="IDUser" Parameter="iDUser" Type="System.String" DbType="NVarChar(30)" />
    <ElementType Name="Sp_MyPostListResult">
      <Column Name="IDPost" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatorIDUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatorUserCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatorName" Type="System.String" DbType="NVarChar(550)" CanBeNull="true" />
      <Column Name="CreatorFamily" Type="System.String" DbType="NVarChar(550)" CanBeNull="true" />
      <Column Name="CreatorAvatar" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="IDApplication" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TitlePicture" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="PostTypeCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PostTypeName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="StateCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StateName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CityCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CityName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PriceForVsit" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ReciveMessage" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PublishDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ExpireDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VisitCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="balabar1_Tubeless_Develop.Sp_postList_loggedin" Method="Sp_postList_loggedin">
    <Parameter Name="IDUser" Parameter="iDUser" Type="System.String" DbType="NVarChar(30)" />
    <ElementType Name="Sp_postList_loggedinResult">
      <Column Name="IDPost" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatorUserCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatorName" Type="System.String" DbType="NVarChar(550)" CanBeNull="true" />
      <Column Name="CreatorFamily" Type="System.String" DbType="NVarChar(550)" CanBeNull="true" />
      <Column Name="CreatorAvatar" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="IDApplication" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TitlePicture" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="PostTypeCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PostTypeName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="StateCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StateName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CityCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CityName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PriceForVsit" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ReciveMessage" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PublishDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ExpireDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VisitCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IsSeen" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="SeenPostID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IDPost1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsFav" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="FavPostID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.FNGetWalletBalanceByUserId" Method="FNGetWalletBalanceByUserId" IsComposable="true">
    <Parameter Name="userId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Decimal" />
  </Function>
</Database>